### ISSUE TITLE
How to use Face ID instead of PIN 

### ISSUE THREAD

**Issue by chrissyw247** [msintuneappsdk/ms-intune-app-sdk-ios#103]
Hi! I'm applying an APP that allows for Face ID instead of a PIN to an iOS app built with Swift. 
I was wondering how you make sure the user doesn't have to both Face ID and enter PIN?

**Comment by Kyle-Reis** [comment]
Hi @chrissyw247, are you asking how the app would ensure this? The Intune SDK should handle prompting the user for FaceID or PIN when needed.

**Comment by chrissyw247** [comment]
Hi! Thanks for replying! The current APP we have applied allows for Face ID instead of PIN - whoever, my app is still requesting PIN. I thought we had to manually add the Face ID?

**Comment by Kyle-Reis** [comment]
Hi @chrissyw247, two questions:

On the device you are testing with, has Face ID been enabled? If the user does not actually have FaceID enabled for the device, or the device does not support it, the Intune SDK will continue to prompt for PIN instead.

Did you follow step 6 of the [integration instructions](https://docs.microsoft.com/mem/intune/developer/app-sdk-ios#build-the-sdk-into-your-mobile-app) to add the [NSFaceIDUsageDescription Info.plist key](https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW75)? iOS requires that this key be present for apps to use FaceID, so that the user may be presented with a localized string explaining what the app uses FaceID for. If this key is not present and the app attempts to use FaceID, the app will crash. Therefore, if the Intune SDK detects that this key is not set, it will prompt for PIN instead.

**Comment by Kyle-Reis** [comment]
Hi @chrissyw247,did the above information help resolve this issue for you?

**Comment by Kyle-Reis** [comment]
Hey @chrissyw247, checking in again on whether this issue is now resolved.

**Comment by Kyle-Reis** [comment]
Hi @chrissyw247, checking in one last time before closing out this issue on whether this is now resolved.

**Comment by Kyle-Reis** [comment]
Closing out this issue due to inactivity. Please reopen if you still need help with this.
