### ISSUE TITLE
MS Intunes integration for React Native and client impact

### ISSUE THREAD

**Issue by jarnakantaria-gep** [msintuneappsdk/ms-intune-app-sdk-ios#125]
Before moving to the integration of MS Intunes on mobile, we have a few queries.
Ours is a react native application that is already live on both google play store and app store.

It is possible that some of our clients might be using Azure AD, while others might not.
a) Will login of non-azure clients be affected adversely?
b) Is it possible to switch off the feature for certain clients even with Azure AD?
c) Will app protection policies (eg. prevention of File Sharing, download of files, saving files to a local device, or print screen) applied for a client with Azure AD affect non-azure AD Clients?

[https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-ios#configure-msal ]
Will prevention of File Sharing, print screen, copy-pasting of text, download of files, saving the file to a local device be supported with React Native? The extensions (for eg. share, action, Notification) are a part of a third-party library

Can we expect MS Intunes integration/ support for React Native in the near future?

**Comment by Kyle-Reis** [comment]
Hi @jarnakantaria-gep, It is possible to support both AAD accounts as well as accounts from other services. Several Microsoft apps and 3rd party apps which support Intune MAM do this. The way you would implement this would be to present users with an option to select an account type before signing in. If the user selects AAD, then you would attempt the Intune enrollment. Otherwise, you would not. 

Question: Does your application support signing in with multiple accounts simultaneously? Or is there only ever a single identity signed into the app at a time?

On iOS, Intune MAM app protection policies do work with React Native apps, however app developers may need to bridge any APIs they need to call from the SDK. I'm not sure if the same is true for Android since I specifically work on the iOS SDK. All policies which the SDK automatically handles will also apply to the logic within other frameworks that the app or extension links to.It's important to note that some policies cannot be enforced by the SDK and it is the app developer's responsibility to query the policy settings and enforce them. One example of this is save-as policy. Before calling an API (either directly or through a 3rd party FW) to save content locally or to a storage service, the app should check if it is allowed by policy. This is covered here: https://docs.microsoft.com/mem/intune/developer/app-sdk-ios#implement-save-as-and-open-from-controls

**Comment by jarnakantaria-gep** [comment]
Hi Kyle,

Thank you for your quick response. 

Here is my understanding.

1. Will login of non-azure clients be affected adversely?
Understanding: It will not affect non AAD users, as they won't be enrolled for Intunes itself.

3. Will prevention of File Sharing, print screen, copy-pasting of text, download of files, saving the file to a local device be supported with React Native? The extensions (for eg. share, action, Notification) are a part of a third-party library.
Understanding: It is supported with React Native and the SDK manages it. However, certain policies like save-as needs to be explicitly enforced by the developers.

Please validate whether my understanding for the above points is correct. However, I could not gather the answers of these 2 queries.
b) Is it possible to switch off the feature for certain clients even with Azure AD?
c) Will app protection policies (eg. prevention of File Sharing, download of files, saving files to a local device, or print screen) applied for a client with Azure AD affect non-azure AD Clients?


Your question: Does your application support signing in with multiple accounts simultaneously? Or is there only ever a single identity signed into the app at a time?
Answer: We support only single identity signing in. The user has to logout to login via another account. 

Also, please let us know if we can expect an SDK support like Xamarin and Cordova.

**Comment by Kyle-Reis** [comment]
Hey @jarnakantaria-gep, your understanding of points 1 and 2 are correct. 

It is possible to support AAD users who are not licensed or targeted with Intune MAM policies by their organization. All Intune-enabled Microsoft apps do this :). The easiest way to do this would be for the application to  perform authentication with MSAL directly, then call the [registerAndEnrollAccount API](https://docs.microsoft.com/mem/intune/developer/app-sdk-ios#apps-that-already-use-adal-or-msal) to silently enroll in Intune. If the enrollment fails because the user is not licensed or targeted with MAM policies, the app can still allow the user access since this is a perfectly valid scenario. App protection policies will not be applied in this scenario and Intune should have no impact on the functionality of the app. The SDK will automatically retry silent enrollment periodically in case the user does become licensed/targeted later on, at which point policies will be applied.

For the non-AAD scenario, since an enrollment never occurs, policies will never be applied and these users should not be affected. However, to ensure the policies applied for a previously signed-in AAD account do not impact a different account that may sign in afterward, the application should call [deRegisterAndUnenrollAccount](https://docs.microsoft.com/mem/intune/developer/app-sdk-ios#deregister-user-accounts) when the user is signed out. 

If the design of the application ever changes such that multiple users can be signed in at once, there is the chance for Intune app protection policies to impact non-Intune users. In that case, the app needs to inform the Intune SDK of which user's context the app is currently in, as mentioned [here](https://docs.microsoft.com/mem/intune/developer/app-sdk-ios#enable-multi-identity-optional). If the app fails to inform the SDK when it has changed from the managed identity's context to an unmanaged identity's context, app protection policies could be incorrectly applied to the unmanaged account.

The only cross-platform technology bindings/bridging we actively maintain and support are the [Intune Xamrin bindings](https://docs.microsoft.com/mem/intune/developer/app-sdk-xamarin). At this time, there aren't any plans to build/maintain a plugin for any other cross-platform technology, but developers can do this themselves, the steps for bridging Native SDKs are usually well documented.

**Comment by jarnakantaria-gep** [comment]
Hi @Kyle-Reis,

Thank you so much for your quick response, your replies is very much helpful for us to analyse.

One more query, can you please help us with the policies that come under developers responsibility to be handled. As we follow this link [](https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-ios#implement-save-as-and-open-from-controls) only Save-as and open-from policies has to be explicitly handled by the developers right?

Also, I am still unable to identify if save as is a part of some third-party library, how can I restrict it.

**Comment by Kyle-Reis** [comment]
Hi @jarnakantaria-gep, for single-identity applications, the developer needs to handle the following in addition to the two policies mentioned above:

[File encryption policy](https://docs.microsoft.com/mem/intune/developer/app-sdk-ios#implement-file-encryption-required)

[Notification policy](https://docs.microsoft.com/mem/intune/developer/app-sdk-ios#notifications) (if notifications are supported by the app)

If your app includes a FileProvider extension, you should also follow the instructions in this section: https://docs.microsoft.com/mem/intune/developer/app-sdk-ios#integrating-a-file-provider-extension

For the rd party save-as scenario, are you calling some API on the third party library to save content? Or does the 3rd party library show some UI that the user can interact with and has the ability to save content?

**Comment by jarnakantaria-gep** [comment]
Hi @Kyle-Reis,

We are using a 3rd party library that opens native view to show the image/ document with the default save as and share native button over the top. 

Will the SDK be able to handle this? If not, how will the developers handle it?

**Comment by Kyle-Reis** [comment]
@jarnakantaria-gep, share functionality should be covered. Depending on how the save functionality is implemented, the SDK may be able to automatically enforce policy on it. Can the user only save to local storage, or are 3rd party cloud services also supported?

**Comment by jarnakantaria-gep** [comment]
Hi @Kyle-Reis,

We support storage on both local devices and 3rd party cloud services like google drive, one drive, iCloud.
So, in such cases would the SDK be able to handle it automatically? 

PS: Client would mostly restrict it to one drive.

**Comment by JarnaKantaria** [comment]
Hi @Kyle-Reis,

Is there any additional cost for MS Intunes SDK integration for the client or for the developer?
Also, we came across this link for app registration, [.](https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-get-started) 
How much time does it take for app registration usually, also, is there any cost associated with registration?

Kindly help us as soon as possible as it is urgent for us.

**Comment by Kyle-Reis** [comment]
Hi @JarnaKantaria, there is no monetary cost associated with registration. Registration is really just a matter of signing the agreement and providing icons for your app as well as app store links to be used in the EndpointManager UI when IT admins are targeting policy. Once agreement is signed and icons/links provided, the Intune team will start the process of adding the app to the UI. Time for your app to begin showing up in the console can vary, depending on the timing of when materials were received relative to the release cadence for EndpointManager. It could take a little over 1 month for the app to begin showing in the UI. However, once you've released a version of the app which supports Intune to the app store, customers can begin targeting policy to it by bundle ID even if it has not yet been added in the UI.

**Comment by Kyle-Reis** [comment]
Closing out this issue. Feel free to reach out again if you have any more questions or encounter any problems with your integration.
