### ISSUE TITLE
Query on using telecommunication with Intune 14.0

### ISSUE THREAD

**Issue by dbanik** [msintuneappsdk/ms-intune-app-sdk-ios#129]
We are in the process of upgrading our app from intune 12 to intune 14.0. While going through the release notes, we came across the following note:

`Added support to route calls to a managed dialer and removed telecommunication (tel/telprompt) protocol from the SDK's default exemption list.`

Our app uses `tel` protocol. Do we need to make any adjustment or use some other api for making telephony calls in future?

**Comment by Kyle-Reis** [comment]
Hi @dbanik, you shouldn't need to make any changes in your app. What that note means is that tenant administrator now have the ability to configure policy to route phone calls made via "tel" links to a specified managed dialer app instead of the native dialer. Apps do not need to make any changes to support this and it should be entirely handled by the SDK. Question: Does your app call canOpenUrl on "tel" URLs before actually attempting to open them? If so, there is a known issue in this scenario which we've already addressed and it should go out in our next release.

**Comment by dbanik** [comment]
Thanks for clarifying. We don't use `canOpenUrl` on "tel" URLs but thanks for stating that out.
