### ISSUE TITLE
Dynamic Library Support Xcode 12.3

### ISSUE THREAD

**Issue by tritter** [msintuneappsdk/ms-intune-app-sdk-ios#130]
**Describe the bug:**
The current version of the IntuneMAM.framework isn't working with the latest release of Xcode.

**To Reproduce**
1. Add to Xcode
2. Try to build

**Expected behavior:**
Is building, what Ive read so far is that you need to split-up the binaries in ARM and Intel!?

**Screenshots and logs:**
![intune error](https://user-images.githubusercontent.com/1229109/102221198-20dfc900-3ee2-11eb-8021-358128fd15fc.png)

**Smartphone (please complete the following information):**
- All

**Intune App SDK for iOS (please complete the following information):**
- Version 14.0.0

**Comment by tritter** [comment]
A workaround for now is to set "Validate Workspace" in your project's build settings to Yes. It will still show a warning, but will build the project.

**Comment by Kyle-Reis** [comment]
Hey @tritter, thanks for reporting this, and thanks for sharing the workaround! We're already working on switching over to shipping our SDK as a set of [xcframeworks](https://developer.apple.com/videos/play/wwdc2019/416/) instead of  universal FAT binaries which contain both simulator and device slices, which should address this.

**Comment by Kyle-Reis** [comment]
@tritter - This issue should be addressed in our [latest release](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/releases/latest) (version 14.1.0)
