### ISSUE TITLE
 fatal error: lipo: input file must be a fat file when the -extract option is specified (No such file or directory)

### ISSUE THREAD

**Issue by arsalangolestanekh** [msintuneappsdk/ms-intune-app-sdk-ios#140]
When I try to upload app to TestFlight, process failed on:
Copying /Users/user/Documents/.../IntuneMAMSwift.xcframework/ios-arm64/IntuneMAMSwift.framework step with following errors: See ERRORS

When I am running app on the device and simulator, everything works good, when I am preparing the build, process fail.
Set Build Active Architecture Only - YES doesn't help. 
Frameworks are Embedded and Signed.

ERRORS:
❌ fatal error: lipo: input file (/Users/name/Library/Developer/Xcode/DerivedData/productname/Build/Intermediates.noindex/ArchiveIntermediates/schem/InstallationBuildProductsLocation/Applications/product.app/Frameworks/IntuneMAMSwift.framework/IntuneMAMSwift) must be a fat file when the -extract option is specified
❌  fatal error: lipo: can't open input file: /Users/name/Library/Developer/Xcode/DerivedData/productname/Build/Intermediates.noindex/ArchiveIntermediates/schem/InstallationBuildProductsLocation/Applications/product.app/Frameworks/IntuneMAMSwift.framework/IntuneMAMSwift-arm64 (No such file or directory)
❌  fatal error: lipo: input file (/Users/name/Library/Developer/Xcode/DerivedData/productname/Build/Intermediates.noindex/ArchiveIntermediates/schem/InstallationBuildProductsLocation/Applications/product.app/Frameworks/IntuneMAMSwiftStub.framework/IntuneMAMSwiftStub) must be a fat file when the -extract option is specified
❌  fatal error: lipo: can't open input file: /Users/name/Library/Developer/Xcode/DerivedData/productname/Build/Intermediates.noindex/ArchiveIntermediates/schem/InstallationBuildProductsLocation/Applications/product.app/Frameworks/IntuneMAMSwiftStub.framework/IntuneMAMSwiftStub-arm64 (No such file or directory)

**Comment by Kyle-Reis** [comment]
Hi @arsalangolestanekh, is the app you are uploading built for multiple architectures? It looks as though some part of the upload process is attempting to extract the arm64 architecture from the Intune framework binary using the macOS lipo command line tool, but per xcframework design, the specific binary within the xcframework only contains a single architecture.

**Comment by arsalangolestanekh** [comment]
Hi, @Kyle-Reis 
Should I remove arm64 architecture?

There are the list of architectures that app supports
<img width="783" alt="arch" src="https://user-images.githubusercontent.com/61407619/107256549-4bfa1b00-6a42-11eb-94ac-04af55c27456.png">

**Comment by arsalangolestanekh** [comment]
@Kyle-Reis 
Before I could use both architectures for Intune SDK.
Is there any way to build for both architectures?

**Comment by Kyle-Reis** [comment]
Hi @arsalangolestanekh, which version of Xcode are you building with and what is the minimum OS target of the app?

**Comment by arsalangolestanekh** [comment]
@Kyle-Reis 
minimum iOS deployment target 12.2 
Xcode 12.3

**Comment by Kyle-Reis** [comment]
@arsalangolestanekh - You should not remove arm64 architecture, as that is the architecture of all devices which support iOS 12.2+. When the standard architectures option shown above is selected, Xcode should not be building the armv7 architecture for your app (even though it is shown in the UI) since there aren't any armv7 devices that support iOS 12.2+.

It seems as though something in the submission process assumes that the Intune SDK binary contains multiple architectures, when it actually only contains a single arm64 architecture. Where are you seeing this error? Could it be from some custom script being executed to extract the arm64 architecture? In previous releases of the Intune SDK, the device and simulator architectures were combined into a single architecture and developers were expected to strip out the simulator archs before app store submission. With xcframeworks in the current release, the simulator and device architectures live within different binaries, and Xcode handles linking the correct one based on the target destination being built for.

**Comment by arsalangolestanekh** [comment]
@Kyle-Reis 
Do you know where can I fix it?

Error appears there: 

Generating 'appName.app.dSYM'
▸ Copying /Users/user/Documents/.../IntuneMAMSwift.xcframework/ios-arm64/IntuneMAMSwift.framework
▸ Copying /Users/user/Documents/.../IntuneMAMSwiftStub.xcframework/ios-arm64/IntuneMAMSwiftStub.framework

▸ Running script 'Run Script'

❌ fatal error: lipo: input file (/Users/name/Library/Developer/Xcode/DerivedData/productname/Build/Intermediates.noindex/ArchiveIntermediates/schem/InstallationBuildProductsLocation/Applications/product.app/Frameworks/IntuneMAMSwift.framework/IntuneMAMSwift) must be a fat file when the -extract option is specified
❌ fatal error: lipo: can't open input file: /Users/name/Library/Developer/Xcode/DerivedData/productname/Build/Intermediates.noindex/ArchiveIntermediates/schem/InstallationBuildProductsLocation/Applications/product.app/Frameworks/IntuneMAMSwift.framework/IntuneMAMSwift-arm64 (No such file or directory)
❌ fatal error: lipo: input file (/Users/name/Library/Developer/Xcode/DerivedData/productname/Build/Intermediates.noindex/ArchiveIntermediates/schem/InstallationBuildProductsLocation/Applications/product.app/Frameworks/IntuneMAMSwiftStub.framework/IntuneMAMSwiftStub) must be a fat file when the -extract option is specified
❌ fatal error: lipo: can't open input file: /Users/name/Library/Developer/Xcode/DerivedData/productname/Build/Intermediates.noindex/ArchiveIntermediates/schem/InstallationBuildProductsLocation/Applications/product.app/Frameworks/IntuneMAMSwiftStub.framework/IntuneMAMSwiftStub-arm64 (No such file or directory)

**Comment by arsalangolestanekh** [comment]
@Kyle-Reis The problem is that IntuneMAMSwift.framework doesn't contain any files with IntuneMAMSwift-arm64 name
Do you have any updates there?

**Comment by Kyle-Reis** [comment]
Hi @arsalangolestanekh, IntuneMAMSwift.framework has never contained a file called IntuneMAMSwift-arm64. Based on the sequence of errors above, my guess is that you have a custom script which attempts to extract arm64 slices from the "IntuneMAMSwift" binary and create this file in doing so. However, since the binary already contains just a single architecture, the command fails, and then subsequent attempt to access the file generated fails as a result.  Same sequence appears to happen for IntuneMAMSwiftStub.

I would start by looking for a "Run script" task under the "Build Phases" tab of your build target's Xcode settings:
![image](https://user-images.githubusercontent.com/7443106/107393890-4562b680-6ac9-11eb-899f-077078faffc9.png)

The contents of any such phase will likely point to the script which needs to be updated.

**Comment by Kyle-Reis** [comment]
Hi @arsalangolestanekh - did the above help you find the root cause of the issue?

**Comment by arsalangolestanekh** [comment]
Hi, @Kyle-Reis,
yeah, the problem was in my script list in build phases.
When I removed interfering script, build went good.
Thank you for help.

**Comment by Kyle-Reis** [comment]
Glad to hear the problem is resolved :)
