### ISSUE TITLE
'IntuneMAMSwift/IntuneMAM.h' not found.

### ISSUE THREAD

**Issue by Manikanta-GEP** [msintuneappsdk/ms-intune-app-sdk-ios#144]
**Describe the bug:**
We are trying to build a library in react-native to use Intune in company apps. But when we integrate library using IntuneMAMSwift.xc framwork we are receiving an error 'IntuneMAMSwift/IntuneMAM.h' not found

<img width="271" alt="Screenshot 2021-02-04 at 4 19 23 PM" src="https://user-images.githubusercontent.com/65960651/108185453-51d2b900-7132-11eb-801e-e64bf1b5f495.png">

Please help us with this.

Thanks.

**Comment by Kyle-Reis** [comment]
Hi @Manikanta-GEP, this error is happening when you attempt to compile the library? Or when attempting to compile an app which links to it?

**Comment by Manikanta-GEP** [comment]
Hi @Kyle-Reis 
First built the library, then added it into actual application through pods, then i am getting this error.

**Comment by Kyle-Reis** [comment]
@Manikanta-GEP -  "IntuneMAMSwift.xcframework" is the framework version of the Intune SDK. It looks like your library is a static library, so linking it to "IntuneMAMSwift.xcframework" creates a dependency on the Intune framework, but does not embed Intune into the binary for your library. To fix this, the app will need to link to IntuneMAMSwift.xcframework to satisfy the dependency of your library.

Alternatively, you could use "libIntuneMAMSwift.xcframework", which is the static lib version of Intune. In this case, Intune will be embedded directly into your static lib and the app will not need to link to it. However, since Intune depends on IntuneMAMSwiftFtub.xcframework, which is not available as a static lib, the app will need to link to this framework in either case.

**Comment by Manikanta-GEP** [comment]
Hi @Kyle-Reis ,
I have tried both the ways you mentioned. Now i am receiving the new error.
<img width="1534" alt="Screenshot 2021-02-18 at 12 54 32 PM" src="https://user-images.githubusercontent.com/65960651/108320771-41c9e080-71e9-11eb-941a-4ff4e12e1f45.png">

Also , please note that i am using bridging header to write the code in Swift. Please let me know if i need to change any import.
Thanks.

**Comment by Kyle-Reis** [comment]
Hi @Manikanta-GEP, for the static library version of Intune (libIntuneMAMSwift.xcframework), to call any Intune APIs from Swift, a bridging header must be used. Could you share what your bridging header import statements look like in this case?

For the framework (IntuneMAMSwift.xcframework), our APIs can be made available in Swift via a simple module import : "import IntuneMAMSwift". It looks like there is a problem with the module import in the first screenshot you shared. Is IntuneMAMSwift.xcframework being linked to the correct build target?

To avoid confusion, I think it might be best to pick the approach that you'd prefer(libIntuneMAMSwift.xcframework or IntuneMAMSwift.xcframework) and work through that solution.

**Comment by Manikanta-GEP** [comment]
Thank you @Kyle-Reis , Am able to solve the issue. Thanks for the help.
