### ISSUE TITLE
Installation via carthage failed due to un-shared schemes 

### ISSUE THREAD

**Issue by AhmedEid** [msintuneappsdk/ms-intune-app-sdk-ios#151]
👋🏽 Trying to install via carthage
```github "msintuneappsdk/ms-intune-app-sdk-ios" "13.0.0"```

Installation fails due to: 
```*** Checking out ms-intune-app-sdk-ios at "13.0.0"
*** xcodebuild output can be found in /var/folders/kl/wvp_ntz15pq7c5ns1qd_flfh0000gp/T/carthage-xcodebuild.wntMXU.log
*** Skipped building ms-intune-app-sdk-ios due to the error:
Dependency "ms-intune-app-sdk-ios" has no shared framework schemes for any of the platforms: iOS```

**Comment by neiljac1** [comment]
Hi @AhmedEid. The Intune SDK is made available as pre-built xcframeworks which can be directly linked into your application. Thank you.

**Comment by Kyle-Reis** [comment]
Closing out this issue. As @neiljac1, the Intune SDK is not an open-source repository which can be configured for installation via Carthage.

**Comment by erikkerber** [comment]
@Kyle-Reis Carthage can be supported by including the zipped xcframeworks in the release assets for each GitHub release.

https://github.com/Carthage/Carthage#archive-prebuilt-frameworks-into-zip-files

One tiny example of this in practice:

https://github.com/bugfender/BugfenderSDK-iOS/releases/tag/1.10.2

I think it would be a welcome addition for many, and might be better for your team since you don't have to commit binaries into Git itself.
