### ISSUE TITLE
Compilation issue Integrating Intune SDK on iOS with MSAL

### ISSUE THREAD

**Issue by parveen-bhatia** [msintuneappsdk/ms-intune-app-sdk-ios#154]
**Describe the bug:**
Intune SDK for iOS has dependency on ADAL pod. In our project we want to use MSAL with Intune SDK.
However if we try to integrate MSAL pod also then there are compilation issues because MSAL and ADAL share common code.

**To Reproduce**
1. Integrate Intune SDK for iOS as mentioned [in developer guide](https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-ios#build-the-sdk-into-your-mobile-app)
2. Integrate ADAL pod (pod 'ADAL', '~> 4.0')
3. Integrate MSAL pod (pod 'MSAL', '~> 1.1')
4. Build the project and see lot of compilation issues as below
<img width="1223" alt="Screen Shot 2021-03-15 at 10 49 52 AM" src="https://user-images.githubusercontent.com/35345044/111172642-5eed9700-857c-11eb-99dc-09c4845ad22f.png">

Seems these issues are happening because MSAL and ADAL share common code like `NSURL+MSIDExtensions.h`

**Expected behavior:**
There shouldn't be any compilation error using Intune SDK with MSAL

**IDE and Libraries Info**
XCode 12.4
Latest version of Intune SDK, ADAL and MSAL

**Comment by Kyle-Reis** [comment]
Hi @parveen-bhatia, MSAL is supported by the Intune SDK, and you should not need to link both ADAL and MSAL (only one or the other). Our [developer guide](https://docs.microsoft.com/mem/intune/developer/app-sdk-ios) has been updated to reference MSAL only, since ADAL is now in maintenance mode and will be deprecated in favor of MSAL.

**Comment by parveen-bhatia** [comment]
I integrated ADAL because `IntuneMAMEnrollmentManager.instance().loginAndEnrollAccount` doesn't prompt for credentials without integrating `ADAL` pod. Also, as mentioned here https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/issues/65 Intune SDK has required dependency on ADAL. Is it true ?

**Comment by Kyle-Reis** [comment]
Hi @parveen-bhatia. At one point, a strict dependency on ADAL for the Intune SDK was true (before MSAL became publicly available), but since then, Intune can use either ADAL or MSAL to acquire a token for enrollment or enforce Intune authentication policy. The recommendation for new apps is to use MSAL. If you are planning on directly authenticating users with MSAL to access some resource in AAD, then the best approach for Intune enrollment would be to call the silent enrollment method (registerAndEnrollAccount) after your app has successfully acquired a token as mentioned here: 

https://docs.microsoft.com/mem/intune/developer/app-sdk-ios#apps-that-already-use-adal-or-msal

Note: You should also [configure Intune to use the same AAD settings as your app](https://docs.microsoft.com/mem/intune/developer/app-sdk-ios#configure-msal-settings-for-the-intune-app-sdk).

**Comment by parveen-bhatia** [comment]
Thanks for clarifications. Fine with closing this issue.

**Comment by Kyle-Reis** [comment]
No problem! Please reach out again if you have any more questions or run into any issues.
