### ISSUE TITLE
How to make unified login flow to the mobile app.

### ISSUE THREAD

**Issue by Naveen-workboard** [msintuneappsdk/ms-intune-app-sdk-ios#163]
Hi,

I'm not sure this is correct place to ask, but I'm looking for a solution for a problem we are facing.
We have our mobile app (iPhone and Android) which has it's own authentication flow to login the users and this is done using SSO. Some vendors of our app use Microsoft corporate accounts for SSO login. Now one vendor is asking us to integrate the MS Intune in the app so that they can apply the policy which they create for their org.

We have followed the guidelines and documentation from here and implemented.

Now we see once our app make SSO login successful, calling (void)loginAndEnrollAccount: (NSString *)identity; API takes user to login again in order to enroll user/app for policy and reterival.

This is kind of making two logins by end user

Is there a way we can unify a single login to our server and also apply policy to our app?

Thanks.

**Comment by Kyle-Reis** [comment]
Hi @Naveen-workboard,  is the app using the ADAL or MSAL library to authenticate AAD users? If so, [registerAndEnrollAccount ](https://docs.microsoft.com/mem/intune/developer/app-sdk-ios#apps-that-already-use-adal-or-msal) should work for your app on iOS.Note: for this to work, you'll also need to follow [these instructions](https://docs.microsoft.com/mem/intune/developer/app-sdk-ios#configure-msal-settings-for-the-intune-app-sdk). To configure the Intune SDK and enable silent enrollment (without prompting). If the app is using another authentication library to authenticate AAD accounts, then unless that library stores AAD tokens in the same location and format as ADAL/MSAL, silent enrollment won't work.

**Comment by Naveen-workboard** [comment]
@Kyle-Reis : Our server authentication is through SSO login (provided by our server). But in order to apply policy on our mobile app, I'm calling MSAL's login API (described [here](https://github.com/AzureAD/microsoft-authentication-library-for-objc)) followed by MS Intune's [loginAndEntrollAccount](https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-ios#apps-that-do-not-use-adal-or-msal) API.  After  loginAndEntrollAccount, policy is getting applied to our app.

This involves two logins on our app.
1. Login to our owner server (in order to serve the services to users)
2. Login to AAD through MSAL library followed by loginAndEntrollAccount API (in order to apply policy on our app).

Since it involves two login flow on our app, we are looking for a unified single login flow where user can authenticate our server and also policy is applied to the app.

Please note that I'm using two libraries in the iOS code
1. MSAL library
2. MS Intune library

**Comment by Kyle-Reis** [comment]
Hi @Naveen-workboard, since your app is performing its own authentication with MSAL before enrolling in Intune, the registerAndEnrollAccount method I mentioned previously is the recommended approach here. loginAndEnrollAccount is meant for apps that don't need to acquire a token from AAD for any purpose other than enrolling in Intune, and so it informs the Intune SDK that it should authenticate the user if cached credentials cannot be found. In the case of your app, where a token is already present in the cache from previous MSAL auth, I suspect this causes Intune to temporarily display some UI before dismissing it without prompting the user. Calling registerAndEnrollAccount will not cause this UI to show.

As for the core issue, it sounds like what you're looking for is a unified auth experience between MSAL/AAD and your own server. I think the [MSAL repository](https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues) might be the best place to ask about this, as Intune does not directly handle authentication (it relies on MSAL to handle it).

**Comment by Naveen-workboard** [comment]
@Kyle-Reis : Thanks.
