### ISSUE TITLE
Duplicate authentication request when using Authenticator App

### ISSUE THREAD

**Issue by joeypatino** [msintuneappsdk/ms-intune-app-sdk-ios#166]
**Describe the bug:**
After authenticating through the MS Authenticator app, the user is required to login again in the `WKWebView` or `SFSafariViewController` in app.

**To Reproduce**
1. Open My App and call `[IntuneMAMEnrollmentManager.instance loginAndEnrollAccount:nil];`. User is redirected to the MS Authenticator app.
2. Authenticate through the MS Authenticator. User is redirected back to My App.
3. Present secure website which requires MS login to access. 
4. The user is requested to login again.

**Expected behavior:**
The user should not be required to authenticate twice.

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: 14.4.2

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version?
**Intune SDK: 14.3.0. MSAL 1.1.16**
- What platform is your app based in (native, Xamarin based, Cordova, etc)?
**Native iOS**

**Additional context:**
I've already had a discussion with the MSAL team here, https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/1284, but we were unable to debug the issue. 

Thanks

**Comment by Kyle-Reis** [comment]
Hi @joeypatino, I've read through the issue you filed with MSAL. Does the app actually have a need to present the webview? It looks like the issue here may be that the webview is handed off to MSAL for authentication, then displayed again a 2nd time by the app with an initial URL of "https://login.microsoftonline.com/common/oauth2?client_id=CLIENT_ID"?

Just a heads up that for apps that use Intune, it is [recommended that applications use WKWebView](https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-ios#special-considerations-when-using-msal-for-app-initiated-authentication) when authenticating with MSAL, and do NOT enable SafariViewControllerBlockedOverride in the IntuneMAMSettings, unless this is deemed to be necessary.

Could you clarify whether the app is initiating auth through MSAL and then calling Intune's registerAndEnrollAccount method, or if it is calling loginAndEnrollAccount to allow Intune to handle initiating MSAL auth if necessary? From the MSAL thread it sounded like the former but here you mentioned you're calling loginAndEnrollAccount?

**Comment by joeypatino** [comment]
Hi @Kyle-Reis, 

A couple answers here: 

Yes the app does need to present the webview. The actual content the user is trying to view is being displayed there. This content is password secured and requires the user to login using their MS account, similar to the setup described here I believe; https://oliverkieselbach.com/2018/03/17/intune-managed-browser-mam-with-azure-ad-application-proxy-and-conditional-access/. 

Also to clarify, the webview that is presented is initialized with the URL for the secure site, not the https://login.microsoftonline.com/common/oauth... URL, but instead of loading that as expected, it redirects to the login page. It would appear that whatever is saved is the keychain is not being found at this point?

---
Regarding using WKWebview vs SFSafariViewController, I'm much happier using WKWebview and can & have rolled back my updates on that. I only switched over to SFSafari since the MSAL team told me that this was required for the brokered SSO to work. I will also disable SafariViewControllerBlockedOverride unless it is found necessary.

While testing with the MSAL team I had the app configured to directly call the MSAL SDKs `acquireTokenWithParameters` and then on success InTune `registerAndEnrollAccount`; using the MSAL `account.username` as the UPN. 

As a separate test, I have also tried authenticating using just the Intune SDK directly. Doing this I call the `loginAndEnrollAccount`. I.E. 
```
    if (IntuneMAMEnrollmentManager.instance.enrolledAccount) {
        [[NSNotificationCenter defaultCenter] postNotificationName:@"presentWebview" object:nil];
    } else {
        [[NSNotificationCenter defaultCenter] postNotificationName:@"presentInitializing" object:nil];
        [IntuneMAMEnrollmentManager.instance loginAndEnrollAccount:nil];
    }
```

But authenticating via MSAL directly or through the Intune SDK still causes the same issue, that the user has to login twice.

**Comment by joeypatino** [comment]
Hi @Kyle-Reis, 
Sorry to push on this, but I was wondering if you had any thoughts on what the issue could be? 

Could this be an issue with the Azure AD configuration for the app or would it only be caused by a misconfiguration in the MSAL / inTune SDKs? I have no insight into the AD configuration since it's controlled by my client and I'm quite at a loss at this point on how to move forward with this.

Thanks again!

**Comment by Kyle-Reis** [comment]
Hi @joeypatino, this does not appear to be an Intune-related problem, as evidenced by the fact that the issue occurs both when the app directly authenticates with MSAL (and then uses silent Intune enrollment, which succeeds) and when calling the Intune interactive enrollment method. I think there may have been some confusion in the thread with the MSAL team about what exactly the problem is in this scenario. 

The issue here is not with enabling single-sign-on between different resources accessed at the application level, but rather with using tokens acquired by the application and stored in the application's keychain to silently authenticate a website within a webview. I'm not sure if this is a supported scenario, but I think the MSAL team would be able to answer that question. I'll reply to the issue filed in the MSAL repo to help bring some clarity here and see if we can figure out what the best approach would be for your scenario.

**Comment by joeypatino** [comment]
Thanks for the input @Kyle-Reis. I’ll wait for the MSAL team to confirm if this flow is supported.

**Comment by vigavadi** [comment]
@joeypatino Just checking if you are still facing issues with MSAL authentication?

**Comment by joeypatino** [comment]
@vigavadi, Yes I am but I have spoken with the MSAL team and they've suggested that I use the SSO extension provided in iOS 13+ to bypass this double authentication. Here's a direct link to the follow up from the MSAL team
https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/1284#issuecomment-894566719

I have not tested this yet since I am waiting on my Client to configure the SSO extension in Azure, so I can't confirm if it will solve the issue.

**Comment by mark-buhagiar** [comment]
sure I'll try my luck 5 years later. @joeypatino do you remember if you'd managed to get this to work please?

**Comment by joeypatino** [comment]
@mark-buhagiar i wish I had something good to tell you but my client at the time decided to change the approach. I don't recall what they did in the end as my contract with them was over shortly after all of this but I know we never found a good solution to this issue.

Again, wish I could help out more, I remember it was a very frustrating situation.

**Comment by mark-buhagiar** [comment]
@joeypatino thanks for even replying mate! You'd hope 5 years later they'd addressed something as basic a request as this (both Apple and Microsoft to be fair!). Have a good one!
