### ISSUE TITLE
Help with MAM for multiple Client ID's

### ISSUE THREAD

**Issue by Abhinay1997** [msintuneappsdk/ms-intune-app-sdk-ios#176]
Expected Workflow:-

1. Custom App with MAM through Intune SDK  is installed from Apple App Store.
2. Upon first launch "AutoEnrollOnLaunch" kicks in and enrolment completes.
3. App Configuration Policy is fetched and enabled.

Clarification:-

Context:- 

Currently we are providing Intune SDK with a particular client's client ID , tenant ID, application ID URI in the IntuneMAMSettings dictionary in Info.plist

Question:- 

Is it possible to use the default client ID which is shipped with Intune SDK and based on the account that is being enrolled, the SDK connects to the required Client ID, tenant ID and applies the required App Config Policy ?

I am guessing MS-Office Apps already have something like this. Could you please clarify how this can be achieved ?

**Comment by Kyle-Reis** [comment]
Hey @Abhinay1997 - If your application is used by multiple customers, then you should define an AAD registration for the app in your own AAD tenant and use that client ID. In the app registration, you should configure the following:

![image](https://user-images.githubusercontent.com/7443106/121724120-6d811700-cab5-11eb-9720-e318004a69fc.png)

This will allow users from any of your customers' tenants to use the app. 

For the Authority URI, you should just allow Intune to use the default common authority. Users will first be prompted for their email address in a generic Microsoft-branded prompt and upon entering it, will be redirected to their specific organization's authentication experience to enter their password.

Notes: 
- When setting up the AAD registration, be sure to add the redirect URI for your app to the new registration. 
- Make sure to follow [these steps ](https://docs.microsoft.com/mem/intune/developer/app-sdk-get-started#give-your-app-access-to-the-intune-app-protection-service-optional) to give your app access to the Intune service.
- Customers will need to approve your application's access to the above within their own tenant. They can approve access on behalf of all users within their tenant when an admin for the tenant signs into the app.
- You should also [register your store app with Microsoft](https://docs.microsoft.com/mem/intune/developer/app-sdk-get-started#register-your-store-app-with-microsoft), so that it can be added to the built-in policy targeting UI in EndPoint manager.

**Comment by Abhinay1997** [comment]
Hey @Kyle-Reis , Thank you for your detailed response. I'll follow these steps and reopen this if I need your help.
