### ISSUE TITLE
App crash on logout (call to deRegisterAndUnenrollAccount method)

### ISSUE THREAD

**Issue by lorenraz** [msintuneappsdk/ms-intune-app-sdk-ios#179]
I'm integrating the SDK into the app. I use the auto-enrollment with the info.plist configurations AutoEnrollOnLaunch and MAMPolicyRequired set to True. So when I start the app, the first thing the user needs to do is  to sign in with his credentials (if there's no available token).
When I try to log out from the app and deregister a user account (call to deRegisterAndUnenrollAccount), I get an error message (image is attached) to restart the app, when I press 'ok' the app crash.

What should be the correct behavior after calling deRegisterAndUnenrollAccount?

I get this error in the logs file:
[connection] nw_read_request_report [C29] Receive failed with error "Connection reset by peer"

I use the latest Intune version, native iOS 14.5

![IMG_0202](https://user-images.githubusercontent.com/20846424/123112709-9b1b7800-d446-11eb-8193-7482ff97b1c6.PNG)

**Comment by Kyle-Reis** [comment]
Hey @lorenraz - this is expected behavior. Unenrollment triggers a selective wipe of the users data which is handled by the SDK and requires that the app be restarted (as mentioned in the alert message). You could potentially implement the [wipeDataForAccount delegate method ](https://docs.microsoft.com/mem/intune/developer/app-sdk-ios#switch-identities) and have the app handle removing all of the user's data. Returning true from the delegate will prevent the restart. You can see an example of this implemented in the [Chatr sample app](https://github.com/msintuneappsdk/Chatr-Sample-Intune-iOS-App/blob/master/chatr/PolicyDelegate.swift).

**Comment by lorenraz** [comment]
Thank you for the quick response! I'll check this out
