### ISSUE TITLE
弹框提示：操作未允许

### ISSUE THREAD

**Issue by slzButton** [msintuneappsdk/ms-intune-app-sdk-ios#200]
**Describe the bug:**
我们今天还出现了一个新的问题，当我们在ios app内用相机拍照后，并对照片进行了编辑操作，然后我们将照片通过我们pickerviewcontroller选择后发送给另一个用户的时候提示我们操作权限有问题，我们有把图片保存到相册

We also had a new problem today. When we took a photo with the camera in the app and edited the photo, we sent the photo to another user after selecting it by our PickerViewController. It reminded us that there was a problem with the operation permission, and we saved the photo to the album

**To Reproduce**
1. Take photos through the camera in the app
2. Edit photos after they are taken
3. Send it to the user
![image](https://user-images.githubusercontent.com/13009437/133379145-a1942764-300a-42a4-a8f2-dd6af13fbee5.png)

**Comment by darosal** [comment]
Hi @slzButton, thank you for reaching out! This message is shown when an app is attempting to send data outside of the app but the user's policies are set to block it.

If this is happening when you save to the photo library/album, then it is expected behavior. This popup is controlled by the **"Send org data to other apps"** policy. To allow saving to the photo library/album, you would need to change the policy value from _"Policy managed apps"_ to _"All apps"_ since the iOS Photos app is not a managed app.

**Comment by slzButton** [comment]
> Hi @slzButton, thank you for reaching out! This message is shown when an app is attempting to send data outside of the app but the user's policies are set to block it.
> 
> If this is happening when you save to the photo library/album, then it is expected behavior. This popup is controlled by the **"Send org data to other apps"** policy. To allow saving to the photo library/album, you would need to change the policy value from _"Policy managed apps"_ to _"All apps"_ since the iOS Photos app is not a managed app.

好的，很感谢您的回复，我们知道该怎么做了
Ok, thank you very much for your reply, we know what to do
