### ISSUE TITLE
Keychain items deleted Error -34018

### ISSUE THREAD

**Issue by tritter** [msintuneappsdk/ms-intune-app-sdk-ios#204]
**Describe the bug:**
Since I'm using Intune after iOS updates especially keychain items are deleted for some users. I store them without a `kSecAttrAccessGroup`. Is there any code or path which may deletes all keychain entries of an app as security measurement which could be faulty after an update? (or of course require a change on my side?)

**To Reproduce**
1. Add Keychain Items using SecItemAdd
2. Update iOS version (most common use case but sometimes it also seems to happen randomly)
3. Request keychain item using SecItemCopyMatching
4. Getting Keychain Error -34018 (not found) also after restart etc. Keychain items seem to be deleted. (And I don't delete them anywhere in my code)

**Expected behavior:**
Keychain items are still there.

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version?
latest 14.7, but also happened releases before.
- What platform is your app based in (native, Xamarin based, Cordova, etc)?
Native, Obj-C.
- For errors during build, does the app build without Intune SDK integration?
Yes
- For errors post build, does the app launch without being Intune SDK integrated?
Yes

**Additional context:**
Maybe this is a side-effect of some Intune security mechanisms?

**Comment by neiljac1** [comment]
Hi @tritter. The Intune SDK does not have any code to delete all keychain entries. It's fine for applications to omit the kSecAttrAccessGroup field in their keychain queries, but it's expected that the keychain entitlements have an application specific keychain access group specified as the first item. The first keychain access group should not be com.microsoft.intune.mam, otherwise the application keys will be stored under Intune's access group.

Some questions:
1) Does your application define its own keychain access group before com.microsoft.intune.mam in the entitlements? 
2) Are you integrating the Intune SDK or are you using the App Wrapper tool?
3) What version of iOS are your users on? Is this only happening on iOS 15?

Note, the -34018 error is actually:
errSecMissingEntitlement                 = -34018,    /* A required entitlement isn't present. */

This usually only happens when trying to access a kSecAttrAccessGroup the application does not have access to, although there were some bugs in much older versions of iOS where this would be returned at other times.

Thanks,
Neil

**Comment by tritter** [comment]
Hi @neiljac1,

Yes that's what I thought too and was my understanding.

1. Yes we do! (But I didn't add it to the query, added it now though, could that be a problem? Apple employee said it shouldn't matter with SecItemCopyMatching)
2. I integrate the Intune SDK (NO Wrapper)
3. It happened before but it seems to happen more often with iOS15, its still just a slight percentage and I only reproduced it during the betas on my device.

Yes I know but I checked that, that seems to be alright.

Thanks,
Thom

**Comment by neiljac1** [comment]
Hi @tritter,

It's not necessary to add the keychain access group to the query, but if it's omitted in a SecItemDelete call the SDK will have to do extra work to make sure its items aren't deleted which can be inefficient.

I don't believe the SDK is causing the -34018 error, but when you hit this error, can you use another application signed the same way but not integrated with the SDK to enumerate all the keychain items it has access to and see if the items can be read?

Thanks,
Neil

**Comment by tritter** [comment]
Hi @neiljac1

Ok thanks a lot for clarification, I will try and reopen if I encounter the issue by myself and am reproduce it that way, thanks for the tipp! 

Thanks,
Thom
