### ISSUE TITLE
Endless Authenticator Loop

### ISSUE THREAD

**Issue by tritter** [msintuneappsdk/ms-intune-app-sdk-ios#206]
**Describe the bug:**
Some users probably after token expiration get into an authenticator loop. They can only end it by reinstalling the app.

**To Reproduce**
1. Trying to get an ADAL token
2. Getting an error. (unfortunately I can't reproduce it and tell you the exact apps, but it didn't happen before 14.7.0)
    /*! When the application waiting for broker is activated ,without broker response. */
    AD_ERROR_TOKENBROKER_RESPONSE_NOT_RECEIVED = 503,

**Expected behavior:**
No looping behaviour, the plan is now to update to 14.7.1, but we want to make sure this problem is fixed? Is there a way to force token expiration?

**Screenshots and logs:**
- If your app is experiencing an issue post build, do you have app logs for the crash itself?
- Unfortunately not, just the error code 503

**Smartphone (please complete the following information):**
 - Device: iPad
 - OS: iOS15

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version?
No, 14.7.0
- What platform is your app based in (native, Xamarin based, Cordova, etc)?
Native, Xcode 12 (so not built with iOS15/Xcode13)

- Who is the customer?
AppStore
- Do you see a trend with it only being reproduced on a specific device?
Multiple devices, randomly seems around 10 people a day (of 1500 user base)

**Comment by tritter** [comment]
@darosal I'm using ADAL 5.0.0 https://github.com/AzureAD/azure-activedirectory-library-for-objc/releases/tag/5.0.0

**Comment by tritter** [comment]
@darosal This message is shown before! the loop ![IMG_0055](https://user-images.githubusercontent.com/1229109/137131447-ab6e87f9-7261-477c-ac02-fbd2e72440c4.PNG)

**Comment by tritter** [comment]
@darosal Hmm no not really, it also seemed to work before on iOS14. No my remediate method looks the same in both cases just added silent(YES/NO):
```
 [[IntuneMAMComplianceManager instance]remediateComplianceForIdentity:enrolledAccount silent:silent];
```

**Comment by darosal** [comment]
@tritter Maybe the issue is with acquireToken calls initiated by the Intune SDK. It might be that the first acquireToken is done by the main app and succeeds and following ones done through remediateComplianceForIdentity are failing. The Intune SDK uses the ADALRedirectURI or ADALRedirectScheme values within the IntuneMAMSettings dictionary in the app's Info.plist for making the acquireToken call.

Would you be comfortable sending a screenshot of that part of the Info.plist just as a sanity check?

**Comment by darosal** [comment]
@tritter I see, those AAD override values are not stored in the NSUserDefaults so that shouldn't be affecting whether they are being passed to the Authenticator app or not. I did want to note that the AAD override values are reset after an unenrollment. Are users being unenrolled prior to any of the Authenticator launches?

**Comment by tritter** [comment]
Hi @tritter  Sorry for my late reply. I found out that whenever I do a reinstall of the App I called the unregistration. (this was triggered because of the missing "didLaunch" user defaults. Because of the unenrollment I'm running into this problem. At the moment Im not running into it anymore after fixing the NSUserdefaults bug. So for now it looks like it is my code which results in the unexpected behaviour. Thanks a lot for the support!
