### ISSUE TITLE
FileProtectionLevel and software level encryption

### ISSUE THREAD

**Issue by SSA111** [msintuneappsdk/ms-intune-app-sdk-ios#241]
Have been looking through the various header files to properly understand the Intune SDK. 
However, the usecases and whether functions needs to be called manually or if it is automatically called 
is not always clear to me. For example, given that a file is being saved to disk via the NSFileManager is it correct
to expect that files are automatically protected with either ""NSFileProtectionCompleteUntilFirstUserAuthentication" or 
"NSFileProtectionComplete", in case an application policy has been defined to encrypt org data. Or do the developer
need to set the appropriate file protection level on NSFileManager manually? 

Also, came across the "protectString" functions in the "IntuneMAMDataProtectionManager", is it equivalent 
to the use case of "encryptFile" in "IntuneMAMFile" that allow developers to optionally software level encrypt 
data / strings? 

Thank you.

**Comment by vigavadi** [comment]
Hey @SSA111! Yes, that is correct. The device level encryption should be applied automatically when "Encrypt org data" is set. No work is required from the app in that case.
The APIs to encrypt/protect data in `IntuneMAMDataProtectionManager` and `IntuneMAMFile` are for additional software level encryption that the apps can use. So, in this case work is required on the app end.

**Comment by SSA111** [comment]
Hi @vigavadi. Thank you for the quick reply and clarification. However, could you please tell me what kind of protection level is  used "NSFileProtectionComplete" or "NSFileProtectionCompleteUntilFirstUserAuthentication", when "Encrypt org data" has been set? Thank you.

**Comment by vigavadi** [comment]
Hey @SSA111 Intune would apply NSFileProtectionComplete unless the application sets MaxFileProtectionLevel in the IntuneMAMSettings dictionary in the Info.plist file. You can find more details here: [Intune settings](https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-ios#configure-settings-for-the-intune-app-sdk)

**Comment by SSA111** [comment]
Hi @vigavadi. Thank you very much for the clarification.

**Comment by vigavadi** [comment]
@SSA111 Just want to confirm if we are good to close this one?

**Comment by EthanBarlow** [comment]
I am using the wrapping tool since my application is built in Flutter and sdk integration did not seem necessary (especially given the need to write a bridge to the native sdk code). It is currently causing app crashes when the user locks their device and the app is trying to access resources like writing to firebase firestore cache or my own on-device cache. Specifically, when trying to play media in the background and update last played data. 

Crash logs seem to indicate this is because NSFileProtectionComplete is the protection class being used. @vigavadi you mentioned setting MaxFileProtectionLevel in the IntuneMAMSettings dictionary in the Info.plist. I would like to use NSFileProtectionCompleteUntilFirstUserAuthentication. Is that possible / would it take affect when using the Intune Wrapping tool?
