### ISSUE TITLE
Swift Package Manager (SPM) Support

### ISSUE THREAD

**Issue by karanshah** [msintuneappsdk/ms-intune-app-sdk-ios#271]
Hello! Can we get Swift Package Manager (SPM) support for this sdk? Since SPM is now not only the Apple recommended way of adding dependency to project but also something most developers use to maintain external projects and dependencies. Thank you!

**Comment by drmarkpowell** [comment]
+1 to this: we won't even consider using this until SPM is supported.

**Comment by iGranDav** [comment]
hello, sorry for the noise but I would strongly push for it too! This will help a lot to stay up to date and since you're already doing proper releases on GitHub with an XCFramework this shouldn't be much.

Here is the documentation for it: https://developer.apple.com/documentation/xcode/distributing-binary-frameworks-as-swift-packages

**Comment by gamble2020** [comment]
Can we please get SPM support asap!

**Comment by mhaatcbrain** [comment]
We would love SPM support as well. It would eliminate all the hassle of updating to a new Intune SDK version :)

**Comment by ShruthiAchutha** [comment]
https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/issues/394 will have the response for this feature request.
