### ISSUE TITLE
Frequent/Errant 'Reconnect to your Organization' Dialog

### ISSUE THREAD

**Issue by LibertyDev18** [msintuneappsdk/ms-intune-app-sdk-ios#277]
**Describe the bug:**
When launching an app that has not been accessed in a couple of days the user is immediately presented with the "Checking you organization's data access requirements for this app" screen for about 30 seconds and is then presented with the "Reconnect to your Organization" dialog.

If the user taps 'Sign in' they will be bounced over to Authenticator and asked to enter their enterprise password for the account and access is restored.

If the user taps 'Close Application' the app is quit and launching again allows them to access the app as expected WITHOUT being prompted to enter enterprise credentials again.

We have an entire suite of apps that are still using Intune SDK 15.4.0 and these apps launch and refresh tokens as expected without being prompted to reconnect to the organization through interactive auth.

Being that tapping 'Close Application' seems to clear this, and that this behavior does not surface on the same device with 15.4.0 apps, leads us to believe that this is a bug and is significantly impacting the user experience of the app as users are following the dialog prompt to 'Sign in' and repeatadly having to interactively re-auth. 

**To Reproduce**
1. Successfully authenticate and manage app with Intune SDK 17.0.0
2. Put the app into the background for a couple days
3. Launch app
4. User is presented with dialog to "Reconnect to your Organization"

**Expected behavior:**
Similar to how apps using Intune SDK 15.4.0, the app should be able to still successfully refresh access tokens after a couple of days of inactivity without forcing the user to manually reconnect to the organization by entering their enterprise credentials.

**Smartphone (please complete the following information):**
 - Device: All iOS Devices (iPad & iPhone)
 - OS: 15.7

**Intune App SDK for iOS (please complete the following information):**
- Intune SDK 17.0.0
- Native iOS development

**Additional context:**
In a couple of cases when bringing the app to the foreground it looked like the "Reconnect to your Organization" dialog was already presented in the background which gave way to the "Checking your organization..." screen to then re-present the dialog to reconnect.

**Comment by Kyle-Reis** [comment]
Hi @LibertyDev18, what you are seeing is an intended change in the way that the offline grace period "block access" action policy is enforced, beginning in [version 16.1.1](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/releases/tag/16.1.1) of the Intune SDK. For clarity, I'm referring to the 2nd policy setting in this list:
![image](https://user-images.githubusercontent.com/7443106/192361093-384ac81d-a137-438d-a77b-777b0644aade.png)

 
Prior to this change, policy enforcement was based solely on whether the device was internet connected, and the timer would only begin after the app was first launched while the device was not connected to the internet.
 
After the change, the "block access" policy now behaves consistently with the "wipe data" offline grace period policy:
 
When the app is brought to the foreground, the SDK checks when the last successful policy checkin occurred, and if the time elapsed exceeds the value provided for this policy setting, it will attempt a policy checkin. If that checkin fails for any reason, user is presented with options to try signing in to refresh their AAD tokens, remove the account, or to close the app. It sounds like some users may have launched their apps after not having used them for some time (perhaps over the weekend?) and were presented with these options due to the initial silent checkin attempt failing for some reason (maybe poor internet connectivity?). The reason that some users are allowed access on the 2nd launch after simply closing the application is because the policy checkin on the 2nd launch succeeded.

**Comment by LibertyDev18** [comment]
Hi @Kyle-Reis, we'll try to get some logs captured to help determine what the failed check-in calls are a result of.

Just to confirm, is there any type of retry logic that is in place to address the temporary network glitch scenario? It would seem that a temporary network failure should never result in this type of enforcement or require this type of user interaction. If we set the grace period to 3 days and the user is driving through a tunnel on day 4...

Having some type of graceful handling of network failures but not blocking access would also align with other guidance on not blocking access when things like app management have not yet been confirmed etc.. It seems far too aggressive to trigger this dialog on a network failure.

We have a diverse app portfolio that consists of apps that are used during a variety of event based scenarios. Natural disaster events as an example. Apps may not be used every 'x' number of days so setting that number without proper error handling would most likely prove to be ineffective.

**Comment by Kyle-Reis** [comment]
Hi @LibertyDev18 - Currently the retry happens after the user authenticates. The purpose for the authentication is to remediate a check-in failure that might have occurred due to the cached AAD token being expired or having been removed from the MSAL cache. Unfortunately, we have no way of knowing when a failure to connect to the Intune service might be because the user is currently in an area with poor internet connectivity, or because the user may have intentionally disconnected or jailbroken the device to prevent policy refreshes (which this policy is specifically guarding against). Ultimately I think this comes down to a decision for organizations on how long of a period of time they are comfortable with users not receiving a policy update before they are blocked from accessing organizational data.

**Comment by LibertyDev18** [comment]
Hi @Kyle-Reis, based on the behavior we are seeing, it would seem like there should be no reason that the policy check-in calls are failing and if they were/are successful it would mitigate a large portion of the issue we're actively seeing. We'll focus on getting logs and get those sent over so we can focus on that part first.

Appreciate your help with this. I'll let you know when we have something to send over.
