### ISSUE TITLE
AADSTS50011: The reply url specified in the request does not match the reply urls configured for the application

### ISSUE THREAD

**Issue by OxyFlax** [msintuneappsdk/ms-intune-app-sdk-ios#29]
I implemented ADAL (v 2.7.9) framework perfectly to get connection with Microsoft Authenticator (6.2.8) within my company ADFS. Now that I implemented Intune SDK, I am having this error message while trying to connect.
![IMG_EC7A4E3FE37D-1](https://user-images.githubusercontent.com/14943003/55634017-de359600-57bd-11e9-8711-8f7ad06bbd75.jpeg)
I have enabled the "DeviceManagementManagedApps.ReadWrite" permission on azure portal (native application). 
I have checked everywhere and the reply urlscheme is the right one (same used with ADAL and working). It's specified in the Info.plist under IntuneMAMSettings -> ADALRedirectScheme. I also tried to override it with `IntuneMAMPolicyManager().aadRedirectUriOverride = kRedirectString`

**Comment by Kyle-Reis** [comment]
Hey @OxyFlax, When you specify the ADALRedirectScheme, are you supplying the full redirect URI? That setting is meant to be used as a substitute for the ADALRedirectUri setting if and only if your app's redirect URI is in the format: scheme://bundle_id. If your Redirect URI is in this format, you should specify the scheme only. If your redirect URI is not in this format, you should use the ADALRedirectUri setting under IntuneMAMSettings to specify the full redirect URI instead. Please see the following link for a description of these two settings:

https://docs.microsoft.com/intune/app-sdk-ios#configure-settings-for-the-intune-app-sdk

Which version of our Xamarin bindings are you using? I think the issue with the dynamic override code you shared is that you are initializing a new instance of the IntuneMAMPolicyManager rather than using the singleton instance. Your code should look like this:

IntuneMAMPolicyManager.Instance.aadRedirectUriOverride = kRedirectString

In version 10.0.1 of our bindings, it should no longer be possible to initialize a separate instance of the policy manager.

**Comment by Kyle-Reis** [comment]
My apologies, I just realized that this issue is for our native SDK and not the Xamarin.iOS bindings, but the same concept applies to my comments about the policy manager. You should use the shared instance, and not instantiate a new one.

**Comment by OxyFlax** [comment]
Thanks for giving this information. Didn't noticed about that. 
Actually the issue came from AutoEnrollOnLaunch and MAMPolicyRequired both set on YES.
Putting them to NO makes it continue as expected.

**Comment by OxyFlax** [comment]
In fact we still have the issue when AutoEnrollOnLaunch and MAMPolicyRequired are both set to YES.
Also we need them to be set to YES in order to enforce protection to the app. Is there any possibility to fix this?

**Comment by OxyFlax** [comment]
I tried the following scenarios with a wiped device (Authenticator last version installed):

- launch my app with AutoEnrollOnLaunch & MAMPolicyRequired to YES in info.plist -> This message appears

- then the following makes it work:
  - I put AutoEnrollOnLaunch & MAMPolicyRequired to NO and connect with Authenticator -> Protection policies retrieved...
  - then I use deRegisterAndUnenroll for my account with wipe: `IntuneMAMEnrollmentManager.instance().deRegisterAndUnenrollAccount(account, withWipe: true)`
  - finally I reinstall the app with AutoEnrollOnLaunch & MAMPolicyRequired to YES -> I connect directly without having to fill my credentials.

Perhaps there's some cache with the keychain group. Anyway there's still the issue if I deploy the app with AutoEnrollOnLaunch & MAMPolicyRequired to YES with users who never enrolled. Any idea @Kyle-Reis ?

**Comment by Kyle-Reis** [comment]
Unenrolling/wiping does not automatically blow away the ADAL cache. We leave it intact because it could still be in use by other apps from the same publisher. However, if you desire that a user be signed out of all your apps when signed out of any single one, you may use ADAL's APIs to clear the cache yourself when the user is signed out/unenrolled or when a selective wipe occurs.

Note: If all apps from a given publisher are uninstalled, the user will be forced to enter credentials on the first re-install

**Comment by OxyFlax** [comment]
The main issue remains the same. If I build the app with AutoEnrollOnLaunch to YES, I cannot proceed after this message.

**Comment by Kyle-Reis** [comment]
Hey @OxyFlax, it sounds to me like something is wrong with how you've specified either the client ID or the Redirect URI. Redirect URIs are associated with specific client IDs, so if the client ID isn't correctly set and we use your custom redirect URI with the default client ID of the SDK, AAD auth will fail. Likewise, if the default redirect URI of the SDK (or some other invalid value) is specified for your custom client ID, auth will fail. 

Are you sure the redirect URI you are using is listed in the AAD app registration that maps to your client ID?

**Comment by OxyFlax** [comment]
@Kyle-Reis How can it be possible that the redirect URI and client ID are not setup properly if it works without AutoenrollAtLaunch at yes?

**Comment by Kyle-Reis** [comment]
Are you enrolling via loginAndEnrollAccount or registerAndEnrollAccount when you remove those settings?

**Comment by OxyFlax** [comment]
Yes registerAndEnrollAccount

**Comment by Kyle-Reis** [comment]
Are you setting the redirect URI in code via the policy manager or in the Info.plist?

**Comment by OxyFlax** [comment]
I have both the same in Info.plist and in code with overriding intuneMAMPolicyManager instance variables.

**Comment by Kyle-Reis** [comment]
And you've verified that the enrollment is successful in the registerAndEnrollAccount scenario? On a clean device with nothing in the cache?

**Comment by OxyFlax** [comment]
Just tried with a fresh device just erased and it works perfectly with `registerAndEnrollAccount` perfectly. Though I tried before this to do it with `AutoEnrollOnLaunch` to YES and it didn't worked with the same error as previously

**Comment by Kyle-Reis** [comment]
Hey @OxyFlax, I will test this scenario out myself just for a sanity check, but my guess is that something is wrong with one or both of the Info.plist setting. In the auto-enroll scenario, the SDK's auto-enroll logic runs before any of the app logic gets a chance to execute, so the dynamic override properties are never set. If you comment out the code which sets the policy manager AAD override properties, then test out the registerAndEnrollAccount case, does it work?

**Comment by OxyFlax** [comment]
@Kyle-Reis just tried and commented all about overriding and it worked as previously with registerAndEnrollAccount (and not when AutoEnrollOnLaunch), with a fresh new device.

**Comment by Kyle-Reis** [comment]
Hey @OxyFlax, I just tested out this scenario of using custom AAD client ID/Redirect URI + AutoEnrollOnLaunch/MAMPolicyRequired and it appears to work fine. Which version of the SDK are you using?

**Comment by OxyFlax** [comment]
Thanks for testing. Sad you were not able to reproduce the issue. I am using the last version of the SDK (11.0.13). Do we have some options to have more logs to be able to send in a ticket for Microsoft?

**Comment by Kyle-Reis** [comment]
@OxyFlax, could you try uploading a copy of your info.plist with values for ADAL settings removed? I'd like to verify that the keys/types all look good. 

Also, for clarification, when reproducing the AutoEnrollOnLaunch issue, are you authenticating via the Authenticator app or in a web view within the app?

**Comment by OxyFlax** [comment]
I was using Authenticator app. 

The issue is fixed. Actually the ADALRedirectScheme was setup in format `scheme://bundle_id` instead of `scheme` only. Though I still don't know why it worked with this setting and AutoEnrollAtLaunch to false. There must be a fix in one side or the other. + Maybe improve the documentation. Thank you very much @Kyle-Reis for your help!
