### ISSUE TITLE
App Conditional Access flow after User Enrollment doesn't work

### ISSUE THREAD

**Issue by parveen-bhatia** [msintuneappsdk/ms-intune-app-sdk-ios#343]
**Describe the bug:**
Enroll the user without App Conditional Access policies. Then apply App Conditional policies. When `refresh token` from MSAL  expires and Intune SDK prompts for re-authentication with Azure AD, then Intune SDK doesn't call `IntuneMAMComplianceDelegate`. Means app is not updated about whether app is compliance with App CA or not. However it works fine when App CA is applied before enrollment.

**To Reproduce**
- Apply Intune app config policy
- Enroll the user
- Apply App CA policy  **Require app protection policy**
- Trigger auth session expiry 
- Intune SDK asks for re-auth
- App is not updated with compliance status from App CA

Note: Currently we are changing the device timezone  to ~10 months in future to trigger it as we don't have an option to logout/un-enroll the user. Is there any option to trigger policy update from App CA from Intune SDK ?

**Expected behavior:**
Intune SDK should update the app about App CA compliance status after enrollment. (like using delegate `IntuneMAMComplianceDelegate`)

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro
 - OS: iOS 16.3

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version?
Yes, using **Intune SDK 17.5.0** with **MSAL 1.2.12**
- What platform is your app based in (native, Xamarin based, Cordova, etc)?
Native

**Other Question** - Is there any way to trigger the App CA policy update either from the Intune SDK or by using Microsoft Authenticator/Company Portal ?

**Comment by neiljac1** [comment]
Hi @parveen-bhatia, Is your application calling IntuneMAMComplianceManager remediateComplianceForIdentity to trigger the authentication flow? The IntuneMAMComplianceDelegate will only get called in this case.

For your other question, you can revoke all user tokens via the admin console. This should trigger an interactive authentication on the next token acquire which would apply the latest CA policies. 
1) Go to: https://endpoint.microsoft.com/#view/Microsoft_AAD_UsersAndTenants/UserManagementMenuBlade/~/AllUsers
2) Select the user
3) Click Revoke sessions

Thanks,
Neil

**Comment by parveen-bhatia** [comment]
@neiljac1 yes, when app calls `remediateComplianceForIdentity` then `IntuneMAMComplianceDelegate` is called.

I see, admins' have to revoke sessions to re-trigger this flow after user enrollment.
But do we have any API which can be called to get that latest App CA compliance status after user enrollment?
And is it recommended every time Admin change App CA policy then they also have to revoke user sessions?

Thanks,
Parveen.

**Comment by neiljac1** [comment]
Hi @parveen-bhatia.

In general, the client doesn't know the CA compliance status. This is determined in the AAD service. A lot of factors can go into the CA compliance evaluation, including device compliance, device type, device location, and APP policies. The client does have the ability to make a service call to determine the APP policy compliance only, but this isn't exposed by the SDK. The best way to know if the app/device is fully compliant is to attempt to acquire a token.

It's not necessary to revoke the user sessions. The new CA policies will take affect when the token expires. Revoking the sessions is just a way to speed this up for testing.

Thanks,
-Neil

**Comment by parveen-bhatia** [comment]
@neiljac1 thanks for the info.

For testing purpose, i revoked session from the server. Even then i couldn't see Intune SDK prompts the user to re-authenticate. Assuming that it will happen with next policy check in i tried to wait for > 30 mins and restart the application. Even then couldn't see Intune SDK prompt the user to re-authenticate.

- Is there a way to trigger Intune SDK prompt to re-authenticate after revoking sessions for testing purpose ?
- Also is possible to enhance the Intune SDK behavior so that it should check for App CA policies frequently like the way it checks for Intune Protection policies ? As waiting for session to expire can take months and till the time App CA policy wouldn't be effective ?

**Comment by neiljac1** [comment]
Hi @parveen-bhatia. Does your application use the IntuneMAMEnrollmentManager registerAndEnrollAccount API or the loginAndEnrollAccount API? If you're using registerAndEnrollAccount, then in general the SDK will not prompt the user to authenticate. It's up to the application to manage the user auth. The SDK will call the IntuneMAMEnrollmentDelegate policyRequestWithStatus method with a IntuneMAMEnrollmentStatusAuthRequired error code if it is unable to silently acquire a token. Your application should either watch for this and prompt the user to authenticate or be periodically attempting to acquire a token on its own. Note that the SDK doesn't ever try to acquire a token for a MAM-CA enabled resource. In your test, if you only enabled the MAM-CA policy and didn't revoke the sessions, then the SDK would continue to successfully acquire a token for its resource. So if your application supports MAM-CA, your app should be acquiring a token for its resource and interactively prompt when needed, or if it gets a ERROR_SERVER_PROTECTION_POLICY_REQUIRED error, call remediateComplianceForIdentity.

The one time the SDK might prompt the user to authenticate on its own (when using registerAndEnrollAccount) is if the offline grace period expires which will block the user from using the app.

With the loginAndEnrollAccount API, the SDK owns authenticating the user. However this doesn't support MAM-CA policy since the SDK doesn't acquire a token for any MAM-CA enabled resources. The loginAndEnrollAccount is typically used by applications which don't rely on AAD authentication. If MAM policy enforcement is needed with these apps, then policy can be enforced on app launch by setting MAMPolicyRequired=YES in the IntuneMAMSettings.

Hope this helps,
Neil

**Comment by parveen-bhatia** [comment]
Hi @neiljac1 , yes it definitely helps to get more details about it.
Our app uses `loginAndEnrollAccount` and also supports `MAM-CA`. Then still app should prompt the user to authenticate interactively without relying on Intune SDK. Is it right ?
And if yes, should app also revoke the user session by using `removeAccount` or `signOut` API's in MSAL
or just authenticating interactively with Azure AD from app would be sufficient.

Thanks,
Parveen.

**Comment by neiljac1** [comment]
Hi @parveen-bhatia. Your application doesn't need to interactively prompt the user to authenticate periodically, but rather attempt to acquire a token silently whenever you need to access a service resource requiring a token. If your application doesn't need to access a service often, then you could periodically attempt to acquire a token silently. If the silent acquire fails, then attempt to acquire a token interactively. There's no need to remove the account or sign out in MSAL.

I'd also recommend switching to registerAndEnrollAccount instead of loginAndEnrollAccount. With registerAndEnrollAccount the SDK will automatically retry enrolling periodically if the enrollment failed for any reason. The loginAndEnrollAccount API just tries enrolling a single time.

Thanks,
Neil

**Comment by parveen-bhatia** [comment]
@neiljac1 when we try to acquire token silently then i am not getting `serverProtectionPoliciesRequired` from MSAL.
So, i think we need to do it interactively only.

**Comment by neiljac1** [comment]
Hi @parveen-bhatia. When this error occurs, your application should call the IntuneMAMComplianceManager remediateComplianceForIdentity. 

Thanks,
Neil

**Comment by neiljac1** [comment]
Hi @parveen-bhatia. The behavior for step 5 depends on whether or not the device has already been registered with the Authenticator application. If the device was previously registered, then in step 2 when you application enrolls and applies MAM Policy, the application would be marked MAM-CA compliant at that point even if there wasn't a MAM-CA policy applied. In this case, step 5 wouldn't return MSALErrorServerProtectionPoliciesRequired since it was already compliant.

So to test this behavior, test this flow on a clean device without the Authenticator application installed. In step 5 you should receive the MSALErrorServerProtectionPoliciesRequired error.

Thanks,
Neil

**Comment by parveen-bhatia** [comment]
@neiljac1 this is not fair ask for users/customer to clean/erase device if it doesn't work.

So, any how with cleaned device state also.
First time, once the user authenticates using MSAL  with MF Authenticator. Then Account would be registered in MF Authenticator.

I think the reason you are asking for erasing device is because MF Authenticator might have been saving account stuff in keychain.

We don't want to rely on clean/erase device as it wouldn't be fair ask for users/customers.
Then in this case what are the options ? 

Thanks,
Parveen.

**Comment by neiljac1** [comment]
Hi @parveen-bhatia. I was suggesting resetting the device for testing purposes only so that you could verify you would receive an MSALErrorServerProtectionPoliciesRequired error after applying MAM-CA policies. There's no reason your customer would need to do this. 

The reason I suggested this is because your device is most likely already registered and if so, your application will be marked as MAM-CA compliant at the time it enrolls into Intune. If you enabled MAM-CA policy after that, you will not get an MSALErrorServerProtectionPoliciesRequired error.

If you want to verify you're getting the MSALErrorServerProtectionPoliciesRequired error, then the MAM-CA policy will need to be enabled prior to your application enrolling into Intune, or you need to make sure the device is not registered with the Authenticator application or at a minimum, the Authenticator application is not installed.

Thanks,
Neil

**Comment by parveen-bhatia** [comment]
@neiljac1 i think MF authenticator also provide an option to remove registered device which i haven't tried out yet.
But another problem is once session is revoked by admin for already registered account in MF Authenticator.
Then on interactively acquiring token MF Authenticator just takes the user back to the app once user select registered account. MF Authenticator doesn't ask for password. And MSAL returns Azure AD success.
Is it issue with MF Authenticator app ?

**Comment by neiljac1** [comment]
Hi @parveen-bhatia. Please reach out to the MSAL team regarding not having to re-enter the password after revoking the user sessions. This sounds like an issue.

Thanks,
Neil
