### ISSUE TITLE
Set MSAL webview type to MSALWebviewTypeAuthenticationSession 

### ISSUE THREAD

**Issue by AceChen1** [msintuneappsdk/ms-intune-app-sdk-ios#360]
Why Intune SDK Auto Enroll way can't set webview type to MSALWebviewTypeAuthenticationSession  when use MSAL?
Can add webview type config in info.plist ?

**Comment by darosal** [comment]
Hi @AceChen1, more information can be found in our docs here: [Special considerations when using MSAL for app-initiated authentication
](https://learn.microsoft.com/mem/intune/developer/app-sdk-ios#special-considerations-when-using-msal-for-app-initiated-authentication).

Issues arise when using the SFSafariViewController, SFAuththenticationSession or ASWebAuthenticationSession web views for MSAL in conjunction with the MAM SDK because of what the MAM SDK does to protect these views. To avoid those issues, we recommend using WKWebView.

Please reopen this issue if you have any further questions!
