### ISSUE TITLE
Intune SDK 17.7.0 - a few questions

### ISSUE THREAD

**Issue by lucac-apps** [msintuneappsdk/ms-intune-app-sdk-ios#362]
The SDK 17.7.0 [release notes ](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/releases)state:
"Provide users the option to retry **_a silent policy check-in_** rather than an interactive authentication when the Offline Grace Period "Block Access" conditional launch timeout has been exceeded, **_in cases where the failure was not caused by invalid or missing AAD tokens_**."

1. How does this silent check-in work?
2. Which cases are triggering it?

"NOTE: [iOS 17 SUPPORT] Running the IntuneMAMFrameworkPatcher tool is now a required integration step. Without this, the app launch will be blocked. See [here](https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-ios#post-build-script) for more details."

3. What is the purpose of this Patcher?
4. What is actually doing?

**Comment by lucac-apps** [comment]
Can any one answer to the first point?

"The SDK 17.7.0 [release notes ](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/releases)state:
"Provide users the option to retry **a silent policy check-in** rather than an interactive authentication when the Offline Grace Period "Block Access" conditional launch timeout has been exceeded, **in cases where the failure was not caused by invalid or missing AAD tokens."**

How does this silent check-in work?
Which cases are triggering it?"

**Comment by Kyle-Reis** [comment]
Hi @lucac-apps, in scenarios where the "Block Access" offline grace period timer has expired AND the Intune SDK was unable to successfully check in with the Intune MAM service for any reason other than expired or missing AAD tokens (which would require re-authentication to resolve), users will now be given an option to retry connecting to the Intune service, rather than being forced to authenticate. One example where this kind of situation might occur might be if the "Block Access" OGP timeout has expired while the user did not use the app over the weekend, and when they launch it during their morning commute, they may temporarily have poor internet connection because their train may be going through a tunnel. Starting with Intune SDK version 17.7.0, users can simply hit a button to retry connecting to the Intune service to regain access to the app, rather than going through an unnecessary interactive authentication.

**Comment by lucac-apps** [comment]
@Kyle-Reis Thanks, for the explanation.

**Comment by LibertyDev18** [comment]
Would it be possible to get some explanation around the second part of the OP's question?

"NOTE: [iOS 17 SUPPORT] Running the IntuneMAMFrameworkPatcher tool is now a required integration step. Without this, the app launch will be blocked. See [here](https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-ios#post-build-script) for more details."

What is the purpose of this Patcher?
What is it actually doing?

I understand that this is no longer required but why was it originally required? What is the patcher doing specifically? It would be nice to understand what, if any, changes there will be in behavior, functionality, compliance, etc. pre and post running the tool to help us make an informed decision as to whether we run the patcher.

**Comment by Kyle-Reis** [comment]
Hi @LibertyDev18, in order to intercept some calls to system APIs to apply policy, the Intune SDK needs to make certain memory addresses writable. In iOS 17, Apple introduced some changes that could prevent the SDK from successfully doing so. The IntuneMAMFrameworkPatcher would modify the binary to ensure the Intune SDK would continue to be allowed to make these memory addresses writable. Our team later received confirmation from Apple that an alternative runtime solution could be used and was considered a reliable approach. Hence, the IntuneMAMFrameworkPatcher requirement was dropped.
