### ISSUE TITLE
Selective data wipe not working upon delete request

### ISSUE THREAD

**Issue by TigerZhong** [msintuneappsdk/ms-intune-app-sdk-ios#369]
Describe the bug
Selective data wipe is not functioning upon requesting a data wipe.

To Reproduce

1. Open Microsoft Intune admin center
2. Select: Apps -> App selective wipe -> Create wipe request
3. Select Intune user and add device to wipe request
4. Wait for wipe request to be completed

Expected behaviour
Intune user should be logged out of the application. In addition, all the app data should be deleted from the local device. It is expected the data wipe to be completed within 15 minutes of the data wipe request.

Actual behaviour
After waiting for several hours upon the wipe request. The data wipe is still not completed. The Intune user is still logged in the app normally.

Smartphone
 - Device: iPhone Xs
 - OS: iOS 16.4.1

Intune App SDK for iOS
Intune SDK 17.3.1

**Comment by darosal** [comment]
Hi @TigerZhong, the command to wipe a device comes down as part of a policy checkin. It would not be expected that this comeplete within 15 minutes of the request as a policy checkin has an interval of 30 minutes in most cases. See this doc on policy delivery timing: https://learn.microsoft.com/intune/apps/app-protection-policy-delivery.

It's also possible the device is not wiping because the policy checkin is failing. A future policy checkin should succeed and receive the wipe command. Please see the following docs for more information on app selective wipe and wiping in general:
https://learn.microsoft.com/intune/apps/apps-selective-wipe
https://learn.microsoft.com/intune/remote-actions/devices-wipe

If you are still experiencing issues with the app selective wipes, please reopen this issue and we can discuss collecting logs from one of the affected devices.
