### ISSUE TITLE
UIActivityController Open In forces MS Word to have read-only access.

### ISSUE THREAD

**Issue by nathantamblin** [msintuneappsdk/ms-intune-app-sdk-ios#388]
**Describe the bug:**
An Intune App Protection Policy of “Send org data to other apps: Policy managed apps” is in force, so when our app supplies a FILE: URL to the iOS UIActivityViewController, and we tap on the target app icon, the target app launches but is supplied a copy of the original file rather than allowing our app’s File Provider extension to provide it.

**To Reproduce:**
Have an App Protection Policy configured with “Send org data to other apps” set to “Policy managed apps”.
In our app, tap the menu for a .docx file on a remote server and choose “Share…”.
The iOS Share Sheet pops up. Tap the MS Word app icon.
MS Word launches but immediately informs the user that the document is read-only and must be saved somewhere in order to be editable.

**Expected behavior:**
When MS Word launches, Word should retrieve the document via our app’s File Provider Extension, and the document is therefore immediately editable. The user does not need to store a copy of the file locally (which infringes the Mobile Security Policies of some of our clients). When the document is closed in Word (or the auto-save period elapses), our app’s File Provider Extension should be invoked to save the file.

**Smartphone (please complete the following information):**
 - Device: All iPhones and iPads. Tested on iPhone 8, iPhone X, iPhone 15 Pro, iPad Pro.
 - OS: Latest public iOS 17.1.1  (the problem has existed since our initial integration with iOS 16).

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using?
   Latest, 18.2.0.
- What platform is your app based in?
  Native, Objective-C.

- Who is the customer?
 Every corporate client that uses our Intune-integrated app with an App Protection Policy set as described above (our banking customers generally do this).

- Do you see a trend with it only being reproduced on a specific device?
 No

**Additional context:**
To the UIActivityViewController, we supply a URL such as file:///private/var/mobile/Containers/Shared/AppGroup/<AppGroupGUID>/File Provider Storage/Test.docx

where <AppGroupGUID> is the Shared Container associated with the host app and its File Provider Extension.

The Xcode debug log shows the following error.
No valid file provider found from URL file:///private/var/mobile/Containers/Data/Application/<App GUID>/tmp/.IntuneMAM/60E1F7D5-E74E-4562-9D55-D0B88E757265/Test.docx

This implies that our supplied URL has been replaced with the Intune SDK’s temporary one, thereby preventing the target app (MS Word) from invoking our File Provider Extension when it uses a NSFileCoordinator to access the URL received via the iOS Open In mechanism.

This all works as expected when signed out of Intune, or if the “Send org data to other apps” setting is “All apps”. But when the setting is “Policy managed apps”, the Intune SDK is probably substituting the supplied file because it needs to encrypt it before passing it to other iOS components and the target app. **Our suggestion is that if the file supplied to the UIActivityViewController has already been encrypted by our app using the Intune SDK, Intune should then leave the URL intact (and behave as if the “Send org data to other apps” setting was “All apps”).** Word would not make a local copy of the file, but it would correctly use the File Provider to access it, and the security issues with a local copy would be alleviated. If the supplied file isn’t already encrypted, the Intune SDK should behave as it does currently.

**Comment by nathantamblin** [comment]
This still happens with the SDK version 19.1, and is a big issue for us. 

This bug forces our clients to store copies of documents within the MS Word app rather than be able to edit them directly on a network folder.

Please re-open.

**Comment by nathantamblin** [comment]
This problem still happens with the Intune SDK 19.2.0.

**Comment by jdevag** [comment]
Thanks @nathantamblin for reporting the issue. Let us investigate this.

**Comment by wangxiaoms** [comment]
Hi @nathantamblin could you setup a minimal sample app in GitHub, then we can test to reproduce and investigate?

**Comment by nathantamblin** [comment]
Hi @wangxiaoms. We can start work on producing a sample app, The repository would need to be private. Is that OK?

**Comment by wangxiaoms** [comment]
@nathantamblin That is fine if you can share access with me.

**Comment by nathantamblin** [comment]
I have created a repository and shared it. Please email me with any questions.

**Comment by wangxiaoms** [comment]
@nathantamblin got it, will test and get back later.

**Comment by wangxiaoms** [comment]
Hi @nathantamblin Thanks for the sample and discussions via email. A quick summary:

As you already noted, at this time Intune does not support open in editing when share policies are set. This is due to the Intune SDK using a temp location for the file during encryption. As mentioned [here](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/issues/77) this behavior is expected and open in place editing is not supported. We looked into your suggestion that Intune leave the file/shared item in place if the item is already encrypted by Intune APIs. However, there is still a concern that the receiving app (Word in this case but could be any app) might overwrite the encrypted data and the data would be unprotected from that point onward. This could lead to a data leak, so Intune does not allow 'in-place' actions for encrypted files/share items.

We do have one possible workaround for the customer that would allow MDM enabled devices to use open-in (see below):
 
More info on the MDM solution for open-in:
•	Apps Protection policy set to "Policy Managed Apps with OS Sharing"
•	Deploy "IntuneMAMUPN" app config to MAM enabled apps
•	Set MDM policy restriction "Blocking viewing corporate documents in unmanaged apps"
Docs here: 
1.	[Manage transferring data between iOS apps](https://learn.microsoft.com/en-us/mem/intune/apps/data-transfer-between-apps-manage-ios#use-open-in-management-to-protect-ios-apps-and-data)
2.	[iOS/iPadOS device settings in Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/configuration/device-restrictions-ios#app-store-doc-viewing-gaming)
