### ISSUE TITLE
User has empty values in IntuneMAMAppConfig

### ISSUE THREAD

**Issue by viwod** [msintuneappsdk/ms-intune-app-sdk-ios#409]
**Describe the bug:**
We have a user that is attempting to pass down app config values to our app. They have set up the correct App Config key:value pairs in their settings for this user. We are subscribed to the NSNotification IntuneMAMAppConfigDidChangeNotification in our app. In the diagnostics logs, it is apparent that these app config values are also present. 

When we receive the IntuneMAMAppConfigDidChange notification, we check first for an enrolled account via IntuneMAMEnrollmentManager.enrolledAccount(). Since we have a valid enrolled account, we then call IntuneMAMAppConfigManager.appConfig(forIdentity: enrolledAccount) to fetch the app config for our enrolled user. However, when we query for a value (i.e. appConfig.stringValue(forKey: "login_hint", queryType: IntuneMAMStringQueryType.any)), we receive a blank value. 

The Intune diagnostics console log suggest that this value is present (attached below), but when we query the app config for the enrolled user, this value appears to be blank. Why is this value blank, and what is causing it to not appear in the user's app config?

**To Reproduce**
1. Add app config key:value pairs within tenant (IntuneMAMUPN, and other app specific app config key:value pairs)
2. Successfully enroll Intune account with app
3. Receive IntuneMAMAppConfigDidChange notification
4. Fetch enrolled account
5. Fetch app config for enrolled account
6. Query app config key from app config
7. Blank value appears

**Expected behavior:**
On step 7., the value for the associated key should return, not a blank value.

**Screenshots and logs:**
Intune Diagnostics Console logs
[IntuneMAMDiagnosticFiles(1).txt](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/files/14567291/IntuneMAMDiagnosticFiles.1.txt)

**Smartphone (please complete the following information):**
 - Device: iPhone
 - OS: iOS 17

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version? Yes (19.1.0)
- What platform is your app based in (native, Xamarin based, Cordova, etc)? Native
- For errors during build, does the app build without Intune SDK integration? N/A
- For errors post build, does the app launch without being Intune SDK integrated? N/A

- Who is the customer?
- Do you see a trend with it only being reproduced on a specific device?

**Additional context:**

**Comment by viwod** [comment]
Hi there, could we get an update on this ticket? We've got a customer experiencing this issue and would like to address this as soon as possible.

**Comment by kanishkaBagga** [comment]
@viwod We're actively working on it and will get back to you as soon as we have more information

**Comment by viwod** [comment]
Thanks. Please do let me know if there's any information I can provide that can be of use here.

**Comment by kanishkaBagga** [comment]
@viwod From the logs its noticed that the “login_hint” app config setting is configured in the MDM app config, and not the MAM app config. The MAM SDK APIs will not consider MDM app config unless we know who the MDM managed user is. This would require https://learn.microsoft.com/en-us/mem/intune/apps/data-transfer-between-apps-manage-ios#example-1-admin-experience-in-intune-or-third-party-mdm-console within the MDM app config settings. It appears that the customer has configured these within MAM app config instead.

This can be addressed this issue in two ways:

Option 1: Configure and target IntuneMAMUPN and IntuneMAMOID in MDM app config, rather than MAM app config. The customer should select “Managed devices” when creating the app config:

![image](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/assets/102013705/02d7ef43-8e23-4079-a43f-fb00dd10fc48)

 


Option 2: Configure and target the “login_hint” within MAM app config settings, rather than MDM app config. The customer should select “Managed apps” in the same UI shown above. 

Note: In general, it is recommended that option 1 be implemented for all users who are being MDM managed. Option 2 makes the “login_hint” app config value available irrespective of device management state. So, the customer may choose to implement both of these, depending on their specific needs.

**Comment by viwod** [comment]
Thanks for the clarification here. We'll relay this suggestion to the customer and see if this works. If we would like to go with option 2 and go the MAM route, what Intune variables do we need to target within the app config policy in addition to our app's variables? Do we only need IntuneMAMUPN?

**Comment by viwod** [comment]
Thanks for the help on this one! Closing this issue as our customer has reported that this has resolved the problem for them.

**Comment by viwod** [comment]
Thanks for the help on this one! Closing this issue as our customer has reported that this has resolved the problem for them.
