### ISSUE TITLE
When sharing a file with UIActivityViewController, the message "Preparing file ..." remains displayed.

### ISSUE THREAD

**Issue by bbdev9805** [msintuneappsdk/ms-intune-app-sdk-ios#424]
**Describe the bug:**
When sharing a file with UIActivityViewController, the message "Preparing file ..." remains displayed. Then wait a few minutes and the file will be shared. The file size of shared files is not large. There was no problem with SDK version 18.2, but this problem has been occurring since version 19.0.

**To Reproduce**
1. Launch Microsoft apps such as OneDrive and Edge.
2. Show Share Extension and select my app.
3. The message "Preparing file ..."  remains displayed.

**Expected behavior:**
"Preparing file ..." message will disappear immediately and the file will be shared.

**Screenshots and logs:**
![スクリーンショット 2024-04-22 11 32 26](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/assets/135770768/eef13b3b-0faf-4782-b74b-fd51a2e55ecf)

**Smartphone (please complete the following information):**
 - iPad Pro 
 - iOS 16, 17

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version?
19.2
- What platform is your app based in (native, Xamarin based, Cordova, etc)?
native
- Do you see a trend with it only being reproduced on a specific device?
No

**Comment by pmod2** [comment]
@bbdev9805 - Kindly contact me directly at my email address- priyankamodi@microsoft.com to provide additional details that might include Personally Identifiable Information (PII), which may not be suitable for public disclosure.
Intune Device ID: 
Application ID: 
Intune Logs ID / Intune Logs: 
Any relevant app logs:

**Comment by pmod2** [comment]
@bbdev9805 - Thankyou for sharing the required logs. 

You mentioned it is working as expected with versions - 17.6.0 and 18.2.0 whereas the issue is only with versions 19.x . Can you also share the diagnostic logs for a working version to validate our theory of the issue.

**Comment by pmod2** [comment]
Thanks for sending the logs over. In the non-working logs, we saw -

 _IntuneMAM: Failed to create item provider for file. Unable to encode object: CRWWebView_ 
 
 CRWWebView is a custom WKWebView object within edge which the SDK is failing to encode. However, this does not explain why the sharing prompt of "preparing file" is shown indefinitely. This logic would likely be handled by the sharing app (edge in this case). 
 But the working scenario logs seem to be different. They seem to suggest the file is being **shared from the custom app to edge.** This would be a different scenario (since the repro steps for non-working logs shows that file is shared via Edge browser share extension) and thus might explain different behavior. 
 
To further investigate, we need an internal repro. Could you please provide the .ipa or code snippet with a repro video recording to show the behaviour on my mail id mentioned above?

**Comment by bbdev9805** [comment]
@pmod2 

I have provided information on the problem scenario and reproduction video via email, so please check it out.

**Comment by bbdev9805** [comment]
The issue was resolved by linking MSAL to the app extension. SDK versions below 19 worked without linking MSAL to the app extension, but it seems that from version 19 onwards, not linking to the extension causes problems. The issue has been resolved, so I will close this issue.
