### ISSUE TITLE
12.0.12 + iOS 13 issue with blocking outgoing requests (Apple Maps)

### ISSUE THREAD

**Issue by mborowiec** [msintuneappsdk/ms-intune-app-sdk-ios#56]
---
name: Outgoing request is not blocked
title: 'Request is not blocked despite policy being set'
labels: ''
assignees: ''

---

**Describe the bug:**
When blocking transfer of the data to other apps, Intune still redirects to Apple Maps.
Alert "Action Not Allowed" is being presented but has no effect. Issue started happening with 12.0.12 SDK and iOS 13.
It used to work as expected in 11.2.0 release.

**To Reproduce**
1. Set data transfer policy to block all send org data to other apps.
2. Execute action on Intune enabled app to open Apple Maps (with MKMapItem.openMaps API)
3. Apple Maps are being open, but when you navigate back to the original app, you see the alert "Action Not Allowed"

**Expected behavior:**
Expectation is not to open Apple Maps and block outgoing data with alert presented.

**Screenshots and logs:**
no screenshots needed

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone XS]
 - OS: [iOS 13.2.2]

**Intune App SDK for iOS (please complete the following information):**
- Intune SDK used: 12.0.12
- iOS 13

**Additional context:**
- We *do not* use UISceneDelegate in our application.

**Comment by Kyle-Reis** [comment]
Hey @mborowiec, I can reproduce this issue as well. It's worth noting that for some basic tasks that don't typically involve sensitive business info, we do make exceptions by default and allow users to transfer data to another app. One such example is allowing users to select phone numbers to make a phone call. This scenario typically doesn't involve sensitive info (phone number), and users could easily type the phone number into the "Phone" app anyway, so Intune would really just be an annoyance to the end-user here and not really provide value for the organization. This scenario may fall into the same category. We're going to work on defining what the expected behavior should be here and address this accordingly.

**Comment by Kyle-Reis** [comment]
@mborowiec, we have addressed this issue on the SDK side and the fix should go out with the next major update. We are still considering adding the maps protocol to the default list of exceptions on the console side. IT admins would then have the ability to remove the scheme from the list of exceptions if they desire, and our SDK will successfully block it.

**Comment by mborowiec** [comment]
great, thank you @Kyle-Reis !

**Comment by Kyle-Reis** [comment]
This issue should be fixed in our [latest release](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/releases/latest) (12.2.0)
