### ISSUE TITLE
SDK failed to connect to the location service to determine the user's endpoint

### ISSUE THREAD

**Issue by chrissyw247** [msintuneappsdk/ms-intune-app-sdk-ios#98]
Hi! I'm getting this error when I call loginAndEnrollAccount() on my identity.

**Comment by Kyle-Reis** [comment]
Hey @chrissyw247, checking in again if you're still experiencing this issue.

**Comment by Kyle-Reis** [comment]
Closing out this issue due to inactivity. Please reopen if you are still experiencing this problem.

**Comment by vladislavitsi** [comment]
Hi! I'm getting just the same error with 11.0.8 SDK version. Everything worked fine until around January 28 2021 and then suddenly broken. I just tried updating Intune SDK to 12.9.0 and the issue is gone. So it looks like the older version was deprecated or something. Could you help understanding what is going on, and in case it was really deprecated, where should I keep track on it?

**Comment by Kyle-Reis** [comment]
Hi @vladislavitsi, this is a known issue that was addressed in [version 12.8.0](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/releases/tag/12.8.0) of the SDK. For more information, you can refer to this [Intune Support Team blog post](https://techcommunity.microsoft.com/t5/intune-customer-success/intune-certificate-updates-action-may-be-required-for-continued/ba-p/1839655). In general, it is recommended that customers keep their apps up-to-date with the latest version of the Intune SDK, to keep up with support for new features, bug fixes, and breaking changes introduced by updates to the platform. You can register to be notified via email when a new release of the SDK is available by selecting the "Watch" button under the "Code" tab of this repository. You can also follow the [Intune Support Team](https://techcommunity.microsoft.com/t5/user/viewprofilepage/user-id/226779) on technet to be notified of breaking changes like this one.
